# Generated by Django 3.0.8 on 2020-07-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=30)),
                ('hotel_room', models.IntegerField()),
                ('hotel_price', models.IntegerField(default=1000)),
                ('hotel_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('no_persons', models.IntegerField()),
                ('no_rooms', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hotel')),
                ('user_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('availability', models.IntegerField()),
                ('hotel_location', models.CharField(max_length=30)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hotel')),
            ],
        ),
    ]
