# Generated by Django 3.0.4 on 2020-07-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200729_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='phonenumber',
            field=models.CharField(default=9876543210, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
