# Generated by Django 3.0.4 on 2020-07-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_hotel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='password',
        ),
    ]
