# Generated by Django 3.0.4 on 2020-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_hotel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='password',
            field=models.CharField(default=1234567890, max_length=100),
            preserve_default=False,
        ),
    ]
