# Generated by Django 3.0.4 on 2020-07-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200730_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotel_log',
            new_name='hotel_login',
        ),
    ]
