# Generated by Django 3.0.4 on 2020-07-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200730_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hotel_login',
        ),
    ]
