# Generated by Django 3.0.4 on 2020-07-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_delete_hotel_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hotel')),
            ],
        ),
    ]
