# Generated by Django 3.0.8 on 2020-08-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200802_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='hotel_location',
        ),
    ]
